name: leodys
description: "Leodys pour les dys !"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 #https://pub.dev/packages/cupertino_icons
  provider: ^6.1.5+1 #https://pub.dev/packages/provider
  image_picker: ^1.2.1 #https://pub.dev/packages/image_picker
  google_mlkit_text_recognition: ^0.15.0 #https://pub.dev/packages/google_mlkit_text_recognition
  path_provider: ^2.1.5 #https://pub.dev/packages/path_provider
  image: ^4.5.0 #https://pub.dev/packages/image
  http: ^1.6.0 #https://pub.dev/packages/http
  connectivity_plus: ^6.1.5 #https://pub.dev/packages/connectivity_plus
  get_it: ^9.2.0 #https://pub.dev/packages/get_it
  dartz: ^0.10.1 #https://pub.dev/packages/dartz
  camera: ^0.11.3
  url_launcher: ^6.3.2
  internet_connection_checker: ^3.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  logger: ^2.6.2
  cunning_document_scanner: ^1.2.3
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.3
  share_plus: ^12.0.1
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^7.1.4
  syncfusion_flutter_datagrid: ^32.1.22
  geolocator: ^14.0.2
  local_auth: ^2.3.0
  mailer: ^6.6.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  flutter_dotenv: ^6.0.0
  speech_to_text_windows: ^1.0.1-beta.16
  manual_speech_to_text: ^1.0.4
  uuid: ^4.5.2
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  tflite_flutter: ^0.11.0
  permission_handler: ^11.4.0
  file_picker: ^10.3.9
  googleapis_auth: ^1.4.0
  webview_flutter: ^4.4.1
  html: ^0.15.4
  flutter_riverpod: ^2.5.1
  pay: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont_wght.ttf

  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
    - .env
    - assets/yolo11n-pose.tflite
#    - assets/models/best_float32.tflite
#    - assets/models/yolo26n_float32.tflite
#    - assets/images/carte_test.jpg
    - assets/models/best_float32.tflite
    - assets/models/yolo26n_float32.tflite
    - assets/
    - assets/images/bills/
    - assets/images/coins/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package